---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Escaló sólo `sepal_width` entre `-1` y `1`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Escaló todos los valores entre `-1` y `1`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Escaló  sólo `sepal_width` entre aproximadamente `-3` y `3`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Escaló todos los valores entre aproximadamente `-3` y `3`
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Escaló todos los valores de forma que sus desviación estándar (`std`) sea
    aproximadamente `1`
  checked: true
name: Problema de escala
