---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Escalou apenas `sepal_width` entre `-1` e `1`
  checked: false
- value: Escalou todos os valores entre `-1` e `1`
  checked: false
- value: Escalou apenas `sepal_width` entre aproximadamente `-3` e `3`
  checked: false
- value: Escalou todos os valores entre aproximadamente `-3` e ` 3`
  checked: true
- value: Escalou todos os valores para que seu desvio padrão (`std`) seja aproximadamente
    `1`
  checked: true
name: Problema de escala
