---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '2'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '3'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '4'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '5'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '6'
  checked: true
name: Cierre de siluetas
