---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O cálculo das distâncias falha
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O cálculo não falha e nada incomum é observado nos resultados
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O cálculo não falha, mas mudanças em `x` são quase despercebidas
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O cálculo não falha, mas mudanças em `y` são quase despercebidas
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O cálculo não falha, mas a distância é quase completamente explicada por
    mudanças em `x`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O cálculo não falha, mas a distância é quase completamente explicada por
    mudanças em `y`
  checked: true
name: Uma régua, por favor
