---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Los miembros de <code>cluster<sub>0</sub></code> están claramente separados
    del resto
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Los miembros de <code>cluster<sub>1</sub></code> están claramente separados
    del resto
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Los miembros de <code>cluster<sub>2</sub></code> están claramente separados
    del resto
  checked: false
name: No sé qué pasó
