---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`iris` tem 4 colunas"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`iris` tem 5 colunas"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`iris` contém informações para 150 observações"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`iris` contém informações para 200 observações"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: o comprimento da sépala (`sepal_length`) é aproximadamente entre 4,5 e 8
    centímetros
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: o comprimento da pétala (`petal_length`) é aproximadamente entre 2,5 e 5
    centímetros
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`iris` tem valores nulos (`nan`) em suas colunas"
  checked: false
name: Olhando para a íris
