---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Os membros do <code>cluster<sub>0</sub></code> est達o claramente separados
    dos demais
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Os membros do <code>cluster<sub>1</sub></code> est達o claramente separados
    dos demais
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Os membros do <code>cluster<sub>2</sub></code> est達o claramente separados
    dos demais
  checked: false
name: N達o sei o que aconteceu
