---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`petal_width` e `petal_length` s達o altamente correlacionadas"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`sepal_width` e `sepal_length` s達o altamente correlacionadas"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`sepal_length` e `petal_width` s達o altamente correlacionadas"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`petal_length` e `sepal_length` s達o correlacionadas"
  checked: true
name: Relacionando tudo
