---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O número de divisões (barras) aumenta
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O número de divisões (barras) permanece constante
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O número de divisões (barras) diminui
  checked: true
name: Na perspectiva da abelha
