---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: '2'
  checked: false
- value: '3'
  checked: false
- value: '4'
  checked: true
- value: '5'
  checked: true
- value: '6'
  checked: true
name: Quando vi silhouette, entendi
